# Generated by Django 5.0.3 on 2024-05-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('categoryDescription', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseUser',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('userDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('equipmentDescription', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('equipmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Induction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('dateCompleted', models.DateField(blank=True, null=True)),
                ('completionStatus', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('equipmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.databaseuser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='induction',
            constraint=models.UniqueConstraint(fields=('userID', 'equipmentName', 'category'), name='unique_induction'),
        ),
    ]
